<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Company>FA SYSTEM TECHNOLOGY VIETNAM CO. LTD</Company>
    <Product>PrinterHub</Product>
    <Version>0.1.0</Version>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>
</Project>
